import { Fira_Code, Geist, Geist_Mono, JetBrains_Mono } from "next/font/google";
import "./globals.css";
import Footer from "@/components/Footer";
import NavbarComponent, { MainNavbar } from "@/components/Navbar";
import { ToastContainer } from "react-toastify";


const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const codeFont = Fira_Code({
  variable: "--font-code",
  subsets: ["latin"],
});

export const metadata = {
  title: "Mediaueue-Booking System",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html
      lang="en"
      className={`${codeFont.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className={`${geistSans.className} min-h-full flex flex-col`}>
      <MainNavbar></MainNavbar>
      {children}
      
      <ToastContainer />
      <Footer></Footer>
      </body>
    </html>
  );
}
